[package]
name = "asset_scanning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorful = "0.2.2"
env_logger = "0.10.1"
structopt = "0.3.26"
log = "0.4.20"
ipnet = "2.9.0"
